server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE #first-service project's application name
          predicates:
            - Path=/user-service/** #사용자가 입력한 조건값
        - id: catalog-service
          uri: lb://CATALOG-SERVICE #second-service project's application name
          predicates:
            - Path=/catalog-service/** #사용자가 입력한 조건값
        - id: order-service
          uri: lb://ORDER-SERVICE #second-service project's application name
          predicates:
            - Path=/order-service/** #사용자가 입력한 조건값, test git hub
          filters:
#            - AddRequestHeader=second-request, second-request-header2 #앞에값이 키값이고 뒤에값이 벨류이다.
#            - AddResponseHeader=second-response, second-response-header2 #앞에값이 키값이고 뒤에값이 벨류이다.
#            - CustomFilter